site_name: Site de Documentation CPGEOM
site_description: Centre de ressources techniques spécialisé en géomatique et systèmes d'information géographique
site_author: CPGEOM Team

# Repository
repo_name: cpgeom_doc
repo_url: https://github.com/votre-utilisateur/cpgeom_doc

theme:
  name: mkdocs

nav:
  - Accueil: index.md
  - Introduction:
    - page1.md
  - Sources de données:
    - page2.md
    - page2.1.md
  - Méthodologie:
    - page3.md
  - Résultats:
    - page4.md
  - Conclusion:
    - page5.md